apps/accounts_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts_app'

urlpatterns = [
	url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts_app/login.html'), name='login'),
	url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
	url(r'^signup/$', views.SignUp.as_view(), name='signup'),
]

apps/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('apps.accounts_app.urls', namespace='accounts_app')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/', views.TestPage.as_view(), name='test'),
    url(r'^thanks/', views.ThanksPage.as_view(), name='thanks'),
    url(r'^posts/', include('apps.posts.urls', namespace='posts')),
    url(r'^groups/', include('apps.groups.urls', namespace='groups')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>Social Forum</title>
	<meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# bootstrap #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Audiowide|El+Messiri" rel="stylesheet">
	{# Master CSS #}
	<link rel="stylesheet" href="{% static 'socialforum/css/master.css' %}">

</head>
<body>
	{# NAVBAR #}
	<nav class="navbar mynav" role="navigation" id='navbar'>
		<div class="container">
			<a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a href="{% url 'posts:create' %}">Post</a></li>
					<li><a href="{% url 'groups:all' %}">Groups</a></li>
					<li><a href="{% url 'groups:create' %}">Create Group</a></li>
					<li><a href="{% url 'accounts_app:logout' %}">Logout</a></li>
				{% else %}
					<li><a href="{% url 'groups:all' %}">Groups</a></li>
					<li><a href="{% url 'accounts_app:login' %}">Log In</a></li>
					<li><a href="{% url 'accounts_app:signup' %}">Sign Up</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>
	
	{# CONTENT #}
	<div class="container mycontent">
		{% block content %}
			
		{% endblock %}
	</div>

	<canvas id="canvas"></canvas>

	
	<script src="{% static "socialforum/js/master.js" %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
	<h1>Welcome to Star Social!</h1>
	<h4>Signup today to join groups and post!</h4>
	<h6 class='text-danger'>(click anywhere below to see stars explode!)</h6>
{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}
	
	<h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}
	<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}